In [1]:
import numpy as np 

In [2]:
# Create an array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# Create an array of 10 5's
a = np.zeros(10)
a[:] = 5
a
# or
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
# Create an array of even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
# Create a 3*3 matrix ranging from 0 to 8
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# Create a 3*3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Using Numpy to generate a random number b/w 0 to 1
np.random.rand(1)

array([0.27534531])

In [42]:
# Using Numpy to generate an array of 25 random numb sampled from a standard normal distribution
np.random.standard_normal(25)
# or 
np.random.randn(25)

array([-1.66898174, -0.51439053,  0.24913266, -0.68045296, -1.12032051,
       -0.66025448,  0.37071171, -1.19930613,  0.09176828,  1.86501793,
       -1.29056462, -0.68978709,  0.42323409,  2.03463861,  2.16837553,
        1.43341158,  0.01291377, -1.04633828, -0.68084212,  1.38025314,
       -0.47362986,  1.60819575, -0.76288028, -2.31281414, -0.90796853])

In [43]:
np.arange(0.01,1.01,0.01).reshape(10,10)
# or
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [23]:
# Create an arrray of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Number Indexing and Selection

In [25]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [28]:
mat[3,4]

20

In [44]:
mat[0:3,1].reshape(3,1)
# or
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [32]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [33]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
# Sum of all value in mat
np.sum(mat)

325

In [46]:
# Standard deviation 
np.std(mat)
# or 
mat.std()

7.211102550927978

In [40]:
# Sum of all colums
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])