# Numpy Practise

In [13]:
import numpy as np

In [14]:
a = np.array([1,2,3]) 
b = np.array([4,5,6],dtype='int8')

In [15]:
# Print elements
print(a)
print(b)

[1 2 3]
[4 5 6]


In [16]:
# Print size of each elements
print(a.itemsize)
print(b.itemsize)

4
1


In [17]:
# Print number of elements
print(a.size)
print(b.size)

3
3


In [18]:
# Print total size
print(a.nbytes)
print(b.nbytes)

12
3


In [19]:
# 1D array
c = np.array([1,2,3])
# 2D array
d = np.array([[4,5,6],[7,8,9]])

In [20]:
print(c)
print(d)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [21]:
# Get dimension
print (c.ndim)
print (d.ndim)

1
2


In [22]:
# Get shape
print(c.shape)
print(d.shape)

(3,)
(2, 3)


### Accessing/Changing specific elements, rows and columns

In [48]:
a = np.array([[1,2,3,4],[4,5,6,7]])

In [49]:
print(a)

[[1 2 3 4]
 [4 5 6 7]]


In [51]:
# Accessing specific element
print(a[1][2])
print(a[1,2])
# Elements can also be accessed using the negative index
print(a[1,-2])

6
6
6


In [52]:
# Assigning a value to a specific element
a[1][2] = 99
print(a)

[[ 1  2  3  4]
 [ 4  5 99  7]]


In [53]:
# Accessing a specific row
print (a[0,:])

[1 2 3 4]


In [54]:
# Accessing a specific cloumn
print (a[:,2])

[ 3 99]


In [55]:
# Printing elements in steps [rowindex,startindex:endindex:stepsize]
# Elements can also be accessed with negative index
print(a[0,0:3:2])
print(a[0,0:-1:2])

[1 3]
[1 3]


#### 3D Arrays

In [57]:
 e = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])

In [58]:
print(e)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [59]:
# Accessing a specific elemnt in the 3D array
# See this as two 2*2 arrays
# First paramter as selecting one of two arrays
# Second paramter as selecting a particular row of selected array
# Thirs paramter as selecting a particualr element in particular row
print(e[1,1,1])

6


In [60]:
print(e[0,:,:])

[[1 2]
 [3 4]]


In [61]:
print(e[:,0,:])

[[1 2]
 [4 5]]


In [62]:
print(e[:,:,1])

[[2 4]
 [5 6]]


In [66]:
print(e.shape)
# Interpret the output of shape as two matrices of size 2*2

(2, 2, 2)


## Initializing different types of array 

In [69]:
# All zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# All ones (by default the data type is float32)
np.ones((2,2),dtype='int16')

array([[1, 1],
       [1, 1]], dtype=int16)

In [72]:
# Fill any number
np.full((2,2),23)

array([[23, 23],
       [23, 23]])

In [76]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [80]:
# Fill the array with given data whose shape is similar to existing array
c = np.full_like(a,4)
print(c)
print(a)

[[4 4 4]
 [4 4 4]]
[[1 2 3]
 [4 5 6]]


In [81]:
# Ramdom decimal numbers
np.random.rand(2,3)

array([[0.38000801, 0.94651724, 0.96817516],
       [0.29990631, 0.57846698, 0.01188002]])

In [83]:
# Ramdom integer numbers
np.random.randint(0,3,(2,3))

array([[0, 0, 0],
       [1, 0, 2]])

In [84]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
# Repeating an array
arr = np.array([[5,5,5]])
print(arr.shape)
rep = np.repeat(arr,2,axis=0)
print (rep)

(1, 3)
[[5 5 5]
 [5 5 5]]


In [96]:
# Array copying is shallow
arr = np.array([5,6,7])
arr2 = arr
arr2[0] = 99
print(arr)
print(arr2)

[99  6  7]
[99  6  7]


In [97]:
# Fix for array copying
arr = np.array([5,6,7])
arr2 = arr.copy()
arr2[0] = 99
print(arr)
print(arr2)

[5 6 7]
[99  6  7]
